version: '3'

services:
  nginx:
    image: eduardobusato51/nginx-desafio
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-desafio
    networks:
      - net_desafio_node_nginx
    ports:
      - "8080:80"
  node:
    image: eduardobusato51/node-desafio
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: node-desafio
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    ports:
      - 3000
    networks:
      - net_desafio_node_nginx
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql-desafio
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: desafionode
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - net_desafio_node_nginx

networks:
  net_desafio_node_nginx:
    driver: bridge
